# Generated by Django 5.2.4 on 2025-08-08 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExameGraduacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_exame', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=200, null=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='core.academia')),
                ('modalidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exames', to='core.modalidade')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.professor')),
            ],
            options={
                'verbose_name': 'Exame de Graduação',
                'verbose_name_plural': 'Exames de Graduação',
                'ordering': ['-data_exame'],
            },
        ),
        migrations.CreateModel(
            name='InscricaoExame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('convidado', 'Convidado'), ('confirmado', 'Confirmado'), ('aprovado', 'Aprovado'), ('reprovado', 'Reprovado')], default='convidado', max_length=15)),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.aluno')),
                ('exame', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.examegraduacao')),
                ('graduacao_pretendida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.graduacao')),
            ],
            options={
                'unique_together': {('exame', 'aluno')},
            },
        ),
        migrations.AddField(
            model_name='examegraduacao',
            name='inscritos',
            field=models.ManyToManyField(related_name='exames_inscritos', through='core.InscricaoExame', to='core.aluno'),
        ),
    ]
