# Generated by Django 5.2.4 on 2025-08-08 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_examegraduacao_inscricaoexame_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='academia',
            name='notificar_graduacao',
            field=models.BooleanField(default=False, help_text='Ativar convites e parabenizações de exames de graduação.'),
        ),
    ]
