# Generated by Django 5.2.4 on 2025-08-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_academia_notificar_graduacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricaoexame',
            name='observacoes',
            field=models.TextField(blank=True, help_text='Feedback do professor em caso de reprovação.', null=True),
        ),
    ]
