# Generated by Django 5.2.4 on 2025-08-08 23:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_inscricaoexame_observacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogMensagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('boas_vindas', 'Boas-Vindas'), ('inadimplencia', 'Inadimplência'), ('baixa_frequencia', 'Baixa Frequência'), ('convite_exame', 'Convite para Exame'), ('aprovacao_exame', 'Aprovação em Exame'), ('reprovacao_exame', 'Reprovação em Exame'), ('outro', 'Outro')], default='outro', max_length=20)),
                ('mensagem', models.TextField()),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('sucesso', models.BooleanField(default=True)),
                ('resposta_gateway', models.TextField(blank=True, null=True)),
                ('academia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_mensagens', to='core.academia')),
                ('aluno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_mensagens', to='core.aluno')),
            ],
            options={
                'verbose_name': 'Log de Mensagem',
                'verbose_name_plural': 'Logs de Mensagens',
                'ordering': ['-data_envio'],
            },
        ),
    ]
