# Generated by Django 4.2.7 on 2025-08-13 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_saas_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicoassinaturasaas',
            name='assinatura',
        ),
        migrations.RemoveField(
            model_name='historicoassinaturasaas',
            name='plano_anterior',
        ),
        migrations.RemoveField(
            model_name='historicoassinaturasaas',
            name='plano_atual',
        ),
        migrations.RemoveField(
            model_name='historicoassinaturasaas',
            name='usuario_responsavel',
        ),
        migrations.DeleteModel(
            name='AssinaturaSaaS',
        ),
        migrations.DeleteModel(
            name='HistoricoAssinaturaSaaS',
        ),
        migrations.DeleteModel(
            name='PlanoSaaS',
        ),
    ]
