# Generated by Django 4.2.7 on 2025-08-13 00:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_assinaturasaas_configuracaosistema_planosaas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoVendas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_site', models.CharField(default='Gestão de Lutas - SaaS', max_length=100)),
                ('subtitulo_site', models.CharField(default='Sistema completo para gestão de academias de artes marciais', max_length=200)),
                ('cor_primaria', models.CharField(default='#007bff', help_text='Cor primária em hexadecimal', max_length=7)),
                ('cor_secundaria', models.CharField(default='#6c757d', help_text='Cor secundária em hexadecimal', max_length=7)),
                ('texto_hero', models.TextField(help_text='Texto principal da página inicial')),
                ('beneficios_destaque', models.TextField(help_text='Benefícios principais do sistema')),
                ('email_contato', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone_contato', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp_contato', models.CharField(blank=True, max_length=20, null=True)),
                ('facebook_url', models.URLField(blank=True, null=True)),
                ('instagram_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('trial_dias', models.PositiveIntegerField(default=14, help_text='Dias de período de teste gratuito')),
                ('mostrar_precos', models.BooleanField(default=True, help_text='Se deve mostrar os preços publicamente')),
            ],
            options={
                'verbose_name': 'Configuração de Vendas',
                'verbose_name_plural': 'Configurações de Vendas',
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('novo', 'Novo'), ('contatado', 'Contatado'), ('qualificado', 'Qualificado'), ('convertido', 'Convertido'), ('perdido', 'Perdido')], default='novo', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_ultimo_contato', models.DateTimeField(blank=True, null=True)),
                ('origem', models.CharField(default='site', help_text='Como o lead chegou ao site', max_length=50)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('plano_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planosaas')),
            ],
            options={
                'verbose_name': 'Lead',
                'verbose_name_plural': 'Leads',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='SessaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100, unique=True)),
                ('data_inicio', models.DateTimeField(auto_now_add=True)),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('duracao_segundos', models.PositiveIntegerField(blank=True, null=True)),
                ('pagina_inicial', models.CharField(blank=True, max_length=200, null=True)),
                ('pagina_final', models.CharField(blank=True, max_length=200, null=True)),
                ('converteu', models.BooleanField(default=False)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendas.lead')),
                ('plano_escolhido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.planosaas')),
            ],
            options={
                'verbose_name': 'Sessão de Venda',
                'verbose_name_plural': 'Sessões de Venda',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='CupomDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(max_length=200)),
                ('desconto_percentual', models.DecimalField(decimal_places=2, help_text='Desconto em porcentagem', max_digits=5)),
                ('desconto_fixo', models.DecimalField(decimal_places=2, default=0, help_text='Desconto fixo em reais', max_digits=10)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('ativo', models.BooleanField(default=True)),
                ('max_usos', models.PositiveIntegerField(blank=True, help_text='Número máximo de usos (deixe em branco para ilimitado)', null=True)),
                ('usos_atuais', models.PositiveIntegerField(default=0)),
                ('desconto_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Valor mínimo da compra para aplicar o desconto', max_digits=10)),
                ('aplicavel_planos', models.ManyToManyField(blank=True, help_text='Planos onde o cupom pode ser aplicado', to='core.planosaas')),
            ],
            options={
                'verbose_name': 'Cupom de Desconto',
                'verbose_name_plural': 'Cupons de Desconto',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
